package org.app.subh.org.app.subh.pattern.facade;

/**
 * Created by subh on 17/04/17.
 */
public class MySqlHealper implements Database{
    public void generateHtmlReport() {
        System.out.println("html report generated by the the mysql.");

    }

    public void generatePdfReport() {
        System.out.println("pdf report generated by the the mysql.");

    }
}
